### ISSUE TITLE
Recommended way for testing Component Mixins

### ISSUE THREAD

**Issue by bryanaka** [alexlafroscia/ember-emotion#25]
Hi, Thanks for your work on this repo!

I am working on integrating this into our app and came across this assertion
https://github.com/alexlafroscia/ember-emotion/blob/master/addon/mixins/inject-styles.js#L19

This is because we have a mixin that is being unit tested and while we can mixin to an Ember Object and test that way, we'd like to stay consistent that this only belongs in a component.

```
const testComponent = Component.extend(implementsAdddressy);

module('Unit | Mixin | Implements Addressy', {
  beforeEach() {
    this.subject = testComponent.create({ <some attrs> }); // fails with assertion above
  }
});
```

I was wondering if you had any patterns for this, otherwise I was curious if it made sense to short-circuit `lookupStyles` to return an empty object if no app instance owner is found.

**Comment by alexlafroscia** [comment]
Ahh, I see the problem here. Sorry about that!

My initial reaction would be to test your component through an Integration style test, rather than a Unit test, since that's the norm for components. A component will have an owner in an integration test.

Another thought would be to avoid injecting the mixing automatically into the `Ember.Component` class. There's a setting available for that. You could disable the automatic injection all the time and just apply the mixin manually here needed, or disable automatic injection only in the test environment.

**Comment by bryanaka** [comment]
how would I go about disabling auto injection? I only see the `extensions.js` file which mixes in via reopen, but not how to avoid that.

**Comment by alexlafroscia** [comment]
Check out the [documented configuration options](https://github.com/alexlafroscia/ember-emotion#configuration-options) -- you'll want to set `injectMixin` to `false` (which is `true` by default).

You could also conditionally change this setting based on the environment -- `EmberApp.env()` returns the current environment as a string, so you could compare against `development`, `test` or `production` to alter the behavior based on the build.

**Comment by bryanaka** [comment]
it was a bit hard to find since it is hidden by default (the config description) - but I see it now. Closing since that is enough get going for now. also need to see how this is affected by the new testing format
